include ':capacitor-android'
if (new File(rootProject.projectDir, 'capacitor-android').exists()) {
    project(':capacitor-android').projectDir = new File(rootProject.projectDir, 'capacitor-android')
} else {
    project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')
}
