include ':capacitor-android'
if (new File(rootProject.projectDir, 'capacitor-android').exists()) {
    project(':capacitor-android').projectDir = new File(rootProject.projectDir, 'capacitor-android')
} else {
    project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')
}

include ':capacitor-local-notifications'
if (new File(rootProject.projectDir, 'capacitor-local-notifications').exists()) {
    project(':capacitor-local-notifications').projectDir = new File(rootProject.projectDir, 'capacitor-local-notifications')
} else {
    project(':capacitor-local-notifications').projectDir = new File('../node_modules/@capacitor/local-notifications/android')
}
